-- =============================================================================
-- TripGenius — Sample / Seed Data
-- =============================================================================
-- PURPOSE:
--   Provides demo records to populate a fresh TripGenius database for:
--     - Local development and testing
--     - UI/UX demonstration and screenshots
--     - API testing without having to register/generate trips manually
--     - CI/CD integration test fixtures
--
-- HOW TO USE:
--   1. Make sure the schema exists first (run schema.sql or start the backend
--      so SQLAlchemy auto-creates the tables via Base.metadata.create_all()).
--   2. Then run this file against the SQLite database:
--
--        sqlite3 backend/tripgenius.db < database/sample_data.sql
--
--   Or with Python:
--        python -c "
--        import sqlite3, pathlib
--        db = sqlite3.connect('backend/tripgenius.db')
--        db.executescript(pathlib.Path('database/sample_data.sql').read_text())
--        db.commit()
--        "
--
-- NOTES:
--   • Passwords below are bcrypt hashes of 'TripGenius@2024' (test password).
--   • UUIDs are static for reproducibility in tests.
--   • AI itinerary JSON is abbreviated for readability — real trips have
--     full day-by-day breakdown generated by Gemini.
--   • All monetary values are in INR (Indian Rupees).
--   • Use INSERT OR IGNORE so re-running this file is safe (idempotent).
-- =============================================================================


-- ---------------------------------------------------------------------------
-- DEMO USERS
-- ---------------------------------------------------------------------------

INSERT OR IGNORE INTO users (
    id, full_name, email, hashed_password,
    bio, country, preferred_budget, preferred_travel_style,
    favourite_destination, eco_travel_score, total_trips,
    is_active, is_verified, created_at, updated_at
) VALUES

-- Demo User 1 — Priya Sharma (adventure traveller)
(
    'usr-demo-001-priya-sharma-uuid36',
    'Priya Sharma',
    'priya.sharma@demo.tripgenius.com',
    '$2b$12$LcK7PqXw9nZm1vR8sE4O3.hashed.bcrypt.placeholder.for.TripGenius2024',
    'Passionate about sustainable travel and off-beat destinations across India.',
    'India',
    'Moderate',
    'Adventure',
    'Ladakh',
    72,
    4,
    TRUE,
    TRUE,
    '2024-01-15 10:30:00',
    '2024-09-01 08:00:00'
),

-- Demo User 2 — Arjun Mehta (family traveller)
(
    'usr-demo-002-arjun-mehta-uuid3600',
    'Arjun Mehta',
    'arjun.mehta@demo.tripgenius.com',
    '$2b$12$LcK7PqXw9nZm1vR8sE4O3.hashed.bcrypt.placeholder.for.TripGenius2024',
    'Love exploring heritage sites with my family. History and culture enthusiast.',
    'India',
    'Premium',
    'Cultural',
    'Rajasthan',
    45,
    7,
    TRUE,
    TRUE,
    '2024-03-22 14:00:00',
    '2024-08-15 09:45:00'
),

-- Demo User 3 — Lakshmi Nair (eco traveller from Kerala)
(
    'usr-demo-003-lakshmi-nair-uuid36',
    'Lakshmi Nair',
    'lakshmi.nair@demo.tripgenius.com',
    '$2b$12$LcK7PqXw9nZm1vR8sE4O3.hashed.bcrypt.placeholder.for.TripGenius2024',
    'Kerala local who loves exploring the backwaters and Western Ghats responsibly.',
    'India',
    'Budget',
    'Eco',
    'Wayanad',
    91,
    12,
    TRUE,
    TRUE,
    '2023-11-10 09:00:00',
    '2024-09-10 07:30:00'
);


-- ---------------------------------------------------------------------------
-- DEMO TRIPS
-- ---------------------------------------------------------------------------

INSERT OR IGNORE INTO trips (
    id, user_id, trip_title, destination, state, district,
    duration_days, travelers_count, budget, travel_style,
    interests, transportation_mode, preferred_accommodation,
    ai_itinerary, itinerary_summary,
    attractions, recommended_hotels, recommended_restaurants,
    local_cuisines, beverages_to_try,
    weather_summary, weather_alerts, packing_checklist, travel_tips,
    estimated_trip_cost, accommodation_cost, food_cost,
    transportation_cost, miscellaneous_cost,
    sustainability_score, carbon_footprint_estimate,
    eco_friendly_recommendations, ai_confidence_score,
    is_favorite, is_public, status, generated_by_ai, generation_model,
    created_at, updated_at
) VALUES

-- Trip 1 — Munnar Weekend Getaway (Priya, Romantic, 3 days)
(
    'trip-demo-001-munnar-priya-uuid36',
    'usr-demo-001-priya-sharma-uuid36',
    'Misty Munnar — A Romantic Tea Trail Escape',
    'Munnar',
    'Kerala',
    'Idukki',
    3,
    2,
    25000.00,
    'Romantic',
    '["tea gardens", "waterfalls", "hill station", "photography"]',
    'Car',
    'Resort',
    -- Abbreviated AI itinerary (real trips have full day-wise breakdown)
    '{
        "day_1": {
            "theme": "Arrival and Tea Gardens",
            "morning": {
                "activity": "Drive from Kochi to Munnar via scenic Cheeyappara Falls",
                "duration": "4 hours",
                "estimated_cost": 800,
                "notes": "Stop at Cheeyappara Falls for photos on the way"
            },
            "afternoon": {
                "activity": "Check-in to resort, visit Kolukkumalai Tea Estate",
                "duration": "3 hours",
                "estimated_cost": 500,
                "notes": "World''s highest organic tea plantation — breathtaking views"
            },
            "evening": {
                "activity": "Sunset at Pothamedu Viewpoint",
                "duration": "2 hours",
                "estimated_cost": 0,
                "notes": "Free entry, arrive 30 min before sunset for best light"
            }
        },
        "day_2": {
            "theme": "Wildlife and Waterfalls",
            "morning": {
                "activity": "Eravikulam National Park — Nilgiri Tahr spotting",
                "duration": "3 hours",
                "estimated_cost": 700,
                "notes": "Book bus safari tickets in advance; park entry included"
            },
            "afternoon": {
                "activity": "Attukad Waterfalls and Kundala Lake boating",
                "duration": "3 hours",
                "estimated_cost": 400,
                "notes": "Pack lunch from resort; lake boating is very scenic"
            },
            "evening": {
                "activity": "Candlelight dinner at resort",
                "duration": "2 hours",
                "estimated_cost": 2000,
                "notes": "Ask resort to arrange special couple setup in advance"
            }
        },
        "day_3": {
            "theme": "Tea Museum and Departure",
            "morning": {
                "activity": "Tea Museum Munnar — history of the estate",
                "duration": "2 hours",
                "estimated_cost": 150,
                "notes": "Tea tasting included in ticket; buy tea leaves for home"
            },
            "afternoon": {
                "activity": "Drive back to Kochi",
                "duration": "4 hours",
                "estimated_cost": 800,
                "notes": "Stop at Echo Point on the way out"
            }
        }
    }',
    'A 3-day romantic escape to Munnar covering tea estates, wildlife, and scenic viewpoints. Budget of Rs 25,000 for 2 travellers with resort stay and private car.',
    -- attractions
    '[
        {"name": "Eravikulam National Park", "description": "Home to the endangered Nilgiri Tahr", "entry_fee": 345},
        {"name": "Kolukkumalai Tea Estate", "description": "World''s highest organic tea plantation", "entry_fee": 200},
        {"name": "Pothamedu Viewpoint", "description": "Panoramic views of tea, coffee, and cardamom plantations", "entry_fee": 0},
        {"name": "Attukad Waterfalls", "description": "Cascading waterfall near Munnar town", "entry_fee": 0}
    ]',
    -- recommended_hotels
    '[
        {"name": "Fragrant Nature Munnar", "location": "Pallivasal, Munnar", "price_per_night": 4500, "rating": 4.3, "type": "Resort"},
        {"name": "Spice Tree Munnar", "location": "Devikulam, Munnar", "price_per_night": 5800, "rating": 4.6, "type": "Boutique Resort"},
        {"name": "Munnar Tea County Resort", "location": "Munnar Town", "price_per_night": 3200, "rating": 4.1, "type": "Hotel"}
    ]',
    -- recommended_restaurants
    '[
        {"name": "Rapsy Restaurant", "location": "Munnar Town", "cuisine": "Kerala", "price_range": "Budget"},
        {"name": "East End Hotel Restaurant", "location": "Munnar", "cuisine": "Kerala/Indian", "price_range": "Moderate"},
        {"name": "Green View Restaurant", "location": "Munnar", "cuisine": "Multi-cuisine", "price_range": "Budget"}
    ]',
    '["Kerala Sadhya", "Puttu and Kadala Curry", "Appam with Stew", "Karimeen Pollichathu"]',
    '["Munnar Tea (fresh from estate)", "Kerala Filter Coffee", "Cardamom Tea"]',
    -- weather_summary
    '{"temperature": 18.5, "feels_like": 16.0, "condition": "Misty and Cool", "humidity": 78, "wind_speed": 12}',
    '[]',
    -- packing_checklist
    '["Light woolens for evenings", "Raincoat/poncho", "Comfortable walking shoes", "Camera with extra battery", "Sunscreen SPF 50+", "Insect repellent"]',
    -- travel_tips
    '["Book Eravikulam bus safari 2 days in advance online", "Carry cash — most small eateries are cash only", "Best tea buying at estate factory shops, not tourist stores", "Early mornings are misty and most photogenic"]',
    -- budget breakdown
    25000.00,
    10500.00,   -- accommodation (42%): 3 nights ~Rs 3500/night
    6250.00,    -- food (25%): Rs 2083/day for 2
    4500.00,    -- transportation (18%): car hire
    3750.00,    -- miscellaneous (15%): tickets, shopping
    78,         -- sustainability score
    45.5,       -- carbon footprint kg CO2
    '["Choose eco-certified resorts", "Use reusable water bottles — avoid plastic", "Walk or cycle within Munnar town", "Buy local handicrafts directly from artisans"]',
    0.92,       -- ai_confidence_score
    TRUE,
    FALSE,
    'planned',
    TRUE,
    'gemini-2.5-flash',
    '2024-08-20 11:30:00',
    '2024-08-20 11:35:00'
),

-- Trip 2 — Jaipur Heritage Circuit (Arjun, Cultural, 4 days)
(
    'trip-demo-002-jaipur-arjun-uuid36',
    'usr-demo-002-arjun-mehta-uuid3600',
    'Jaipur — Royal Rajasthan Family Heritage Tour',
    'Jaipur',
    'Rajasthan',
    'Jaipur',
    4,
    4,
    60000.00,
    'Cultural',
    '["heritage", "architecture", "history", "local cuisine", "family"]',
    'Train',
    'Hotel',
    -- Abbreviated day-wise itinerary
    '{
        "day_1": {
            "theme": "Arrival and Pink City Exploration",
            "morning": {"activity": "Arrive by Rajdhani Express, check-in heritage hotel", "estimated_cost": 0},
            "afternoon": {"activity": "Hawa Mahal and Jantar Mantar", "estimated_cost": 500},
            "evening": {"activity": "Chokhi Dhani cultural village dinner", "estimated_cost": 4000}
        },
        "day_2": {
            "theme": "Amber Fort and Jal Mahal",
            "morning": {"activity": "Amber Fort — elephant ride and palace tour", "estimated_cost": 3200},
            "afternoon": {"activity": "Panna Meena ka Kund stepwell, Jal Mahal photography", "estimated_cost": 200},
            "evening": {"activity": "Nahargarh Fort sunset", "estimated_cost": 200}
        },
        "day_3": {
            "theme": "City Palace and Markets",
            "morning": {"activity": "City Palace Museum guided tour", "estimated_cost": 2200},
            "afternoon": {"activity": "Johari Bazaar gem shopping and local lunch", "estimated_cost": 1500},
            "evening": {"activity": "Light and sound show at Amber Fort", "estimated_cost": 600}
        },
        "day_4": {
            "theme": "Day Trip to Abhaneri Stepwell and Departure",
            "morning": {"activity": "Drive to Abhaneri Chand Baori stepwell (1.5 hrs)", "estimated_cost": 800},
            "afternoon": {"activity": "Return and departure by evening train", "estimated_cost": 0}
        }
    }',
    'A 4-day family heritage tour of Jaipur covering forts, palaces, markets, and Rajasthani culture. Budget of Rs 60,000 for 4 travellers including train fare and heritage hotel.',
    '[
        {"name": "Amber Fort", "description": "Magnificent Rajput hilltop palace", "entry_fee": 550},
        {"name": "Hawa Mahal", "description": "Palace of Winds — 953 windows", "entry_fee": 50},
        {"name": "City Palace", "description": "Royal palace with textile museum", "entry_fee": 500},
        {"name": "Jantar Mantar", "description": "UNESCO astronomical observatory", "entry_fee": 200}
    ]',
    '[
        {"name": "Jai Mahal Palace Hotel", "location": "Jacob Road, Jaipur", "price_per_night": 7500, "rating": 4.5, "type": "Heritage Hotel"},
        {"name": "Samode Haveli", "location": "Gangapole, Jaipur", "price_per_night": 6000, "rating": 4.4, "type": "Heritage Hotel"},
        {"name": "ITC Rajputana", "location": "Palace Road, Jaipur", "price_per_night": 9000, "rating": 4.6, "type": "Luxury Hotel"}
    ]',
    '[
        {"name": "Laxmi Misthan Bhandar (LMB)", "location": "Johari Bazaar", "cuisine": "Rajasthani", "price_range": "Budget"},
        {"name": "Suvarna Mahal", "location": "Rambagh Palace", "cuisine": "Rajasthani Royal", "price_range": "Luxury"},
        {"name": "Chokhi Dhani", "location": "Tonk Road", "cuisine": "Rajasthani Traditional", "price_range": "Moderate"}
    ]',
    '["Dal Baati Churma", "Laal Maas", "Ghewar", "Pyaaz Kachori", "Ker Sangri"]',
    '["Lassi from Laxmi Misthan Bhandar", "Masala Chai", "Aam Panna", "Jaljeera"]',
    '{"temperature": 26.0, "feels_like": 24.5, "condition": "Clear and Sunny", "humidity": 35, "wind_speed": 8}',
    '["October to March is ideal; avoid summer (April-June) for extreme heat"]',
    '["Light cotton clothes (morning/afternoon)", "Shawl for cool evenings", "Comfortable walking shoes", "Sunscreen and hat", "Cash for bazaar shopping"]',
    '["Pre-book Amber Fort tickets online to avoid queues", "Hire a government-approved heritage guide at Amber Fort", "Bargain respectfully in bazaars — start at 50% of asking price", "Photography fees are extra at City Palace"]',
    60000.00,
    24000.00,   -- accommodation (40%): 4 nights for 4 people
    15000.00,   -- food (25%): Rs 3750/day for 4
    12600.00,   -- transportation (21%): train + local
    8400.00,    -- miscellaneous (14%): tickets, shopping
    55,
    320.0,      -- train travel carbon
    '["Take trains instead of flights for inter-city travel", "Choose heritage hotels supporting local artisans", "Buy handcrafted souvenirs from government emporiums", "Walk or take cycle-rickshaws within old city"]',
    0.89,
    FALSE,
    TRUE,
    'completed',
    TRUE,
    'gemini-2.5-flash',
    '2024-07-10 09:00:00',
    '2024-07-14 18:00:00'
),

-- Trip 3 — Wayanad Eco Trek (Lakshmi, Eco/Adventure, 2 days)
(
    'trip-demo-003-wayanad-lakshmi-uuid',
    'usr-demo-003-lakshmi-nair-uuid36',
    'Wayanad — Into the Forest: An Eco Trek',
    'Wayanad',
    'Kerala',
    'Wayanad',
    2,
    1,
    8000.00,
    'Eco',
    '["trekking", "wildlife", "tribal culture", "waterfalls", "nature"]',
    'Bus',
    'Homestay',
    '{
        "day_1": {
            "theme": "Arrival and Edakkal Caves Trek",
            "morning": {"activity": "KSRTC bus from Calicut to Kalpetta", "estimated_cost": 250},
            "afternoon": {"activity": "Edakkal Caves — Neolithic rock carvings trek", "estimated_cost": 350},
            "evening": {"activity": "Tribal art workshop at Uravu Bamboo Village", "estimated_cost": 200}
        },
        "day_2": {
            "theme": "Chembra Peak Trek and Departure",
            "morning": {"activity": "Chembra Peak half-day trek (heart-shaped lake)", "estimated_cost": 600},
            "afternoon": {"activity": "Kuruva Island bamboo raft back to Kalpetta, bus home", "estimated_cost": 450}
        }
    }',
    'A budget-friendly 2-day eco-trekking trip in Wayanad exploring caves, tribal culture, wildlife, and waterfalls — all via public transport.',
    '[
        {"name": "Edakkal Caves", "description": "Prehistoric Neolithic rock carvings", "entry_fee": 175},
        {"name": "Chembra Peak", "description": "Highest peak in Wayanad with heart-shaped lake", "entry_fee": 300},
        {"name": "Kuruva Island", "description": "Protected river delta for bamboo rafting", "entry_fee": 175},
        {"name": "Uravu Bamboo Village", "description": "Eco-tourism center for bamboo crafts", "entry_fee": 100}
    ]',
    '[
        {"name": "Vythiri Ripple Resort", "location": "Vythiri, Wayanad", "price_per_night": 2800, "rating": 4.2, "type": "Eco Resort"},
        {"name": "Local Tribal Homestay (Mananthavady)", "location": "Mananthavady", "price_per_night": 1200, "rating": 4.5, "type": "Homestay"}
    ]',
    '[
        {"name": "Pepper County Restaurant", "location": "Kalpetta", "cuisine": "Kerala", "price_range": "Budget"},
        {"name": "Paadhi (Forest Dept canteen)", "location": "Chembra entry point", "cuisine": "Simple Kerala", "price_range": "Budget"}
    ]',
    '["Bamboo Rice (Mulayari) Kanji", "Puttu and Kadala Curry", "Tapioca with fish curry", "Wild honey"]',
    '["Black tea with cardamom", "Bamboo rice gruel", "Fresh coconut water"]',
    '{"temperature": 21.0, "feels_like": 19.5, "condition": "Partly Cloudy with Light Drizzle", "humidity": 85, "wind_speed": 10}',
    '["Light rain expected in evenings — carry a poncho"]',
    '["Trekking shoes (waterproof)", "Raincoat", "Insect repellent (DEET)", "Reusable water bottle", "First aid kit", "Torch/headlamp"]',
    '["Register at forest checkpost for Chembra trek by 8 AM", "Book KSRTC bus tickets online to save money", "Carry your own food for Chembra trek — no stalls en route", "Do not disturb wildlife — maintain silence in forest zones"]',
    8000.00,
    2400.00,    -- accommodation (30%): 1 night budget homestay
    2000.00,    -- food (25%)
    1760.00,    -- transportation (22%): bus fares
    1840.00,    -- miscellaneous (23%): entry tickets, eco shopping
    95,
    12.5,       -- very low carbon (public transport)
    '["Use KSRTC public bus for all travel", "Stay at local homestays to directly support tribal economy", "Buy bamboo handicrafts from Uravu to support artisans", "Carry reusable containers and avoid all single-use plastic"]',
    0.95,
    TRUE,
    FALSE,
    'completed',
    TRUE,
    'gemini-2.5-flash',
    '2024-06-05 07:00:00',
    '2024-06-06 20:00:00'
);


-- =============================================================================
-- VERIFICATION QUERIES
-- (Run these manually to confirm data was inserted correctly)
-- =============================================================================
--
-- SELECT id, full_name, email, total_trips, eco_travel_score FROM users;
-- SELECT id, trip_title, destination, budget, status FROM trips;
-- SELECT COUNT(*) AS total_users FROM users;
-- SELECT COUNT(*) AS total_trips FROM trips;
--
-- =============================================================================
